name: Create Release branch

on:
  workflow_dispatch

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Create branch
        # https://github.com/marketplace/actions/create-branch
        uses: peterjgrainger/action-create-branch@v2.2.0 
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
