name: Create Release branch and PR

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch name'     
        required: true
        default: 'release-v0.0.0'

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Create branch
        # https://github.com/marketplace/actions/create-branch
        uses: peterjgrainger/action-create-branch@v2.2.0 
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          branch: ${{ inputs.branch_name }}
          
  create-pull-request:
    runs-on: ubuntu-latest
    needs: create-branch

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch_name }}
      - name: Create Pull Request
        # https://github.com/marketplace/actions/create-pull-request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.TOKEN }}
          commit-message: Test commit message
          title: Test title
          body: Test body
#           base: main
#           branch: ${{ inputs.branch_name }}
          assignees: Jaewon-Yun
          draft: true
          
