name: Create Release branch

on:
  workflow_dispatch

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Create branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
#       - name: Checkout
#         uses: actions/checkout@v3
#       - name: Create release branch
#         run: git checkout -b release-candidate
#       - name: Push branch
#         run: git push origin release-candidate

