name: Create Release branch

on:
  workflow_dispatch

jobs:
  create-branch:
    name: Create Release branch
    runs-on: ubuntu-latest

    steps:
      - name: Create Branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
