name: Deploy to cocoapods

on:
  pull_request:
    branches:
      - main
    types: [ closed ]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    name: Deploy to cocoapods
    runs-on: macos-latest

    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6
      - name: Extract deployment version
        run: echo "TAG=$(echo '${{ steps.branch-name.outputs.current_branch }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v3
      - name: Tagging deployment version
        run: |
          git tag ${{ env.TAG }}
          git push origin ${{ env.TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      - name: Deploy to cocoapods
        run: pod trunk push Keychaining.podspec
        
