name: Deploy to cocoapods

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to cocoapods
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # release branch 에서 deployment_version 추출
      - name: Tagging deployment version
        run: |
          git tag ${{ deployment_version }}
          git push origin ${{ deployment_version }}
      - name: Deploy to cocoapods
        run: pod trunk push Keychaining.podspec
        
